import type { Metadata } from "next";

// Social sharing / SEO metadata. Relative URLs resolve against metadataBase
// (NEXT_PUBLIC_SITE_URL) set in the root layout.

export const SITE_NAME = "NEXORA";
export const SITE_TITLE = "NEXORA — Everything. One Place.";
export const SITE_DESCRIPTION =
  "Shop 100% authentic electronics, fashion, beauty, home and pantry essentials in Pakistan. Cash on Delivery, Easypaisa, JazzCash and fast delivery.";

/** Default share image (public/og/nexora-og.png, generated by scripts/generate-og.mjs). */
export const DEFAULT_OG_IMAGE = { url: "/og/nexora-og.png", width: 1200, height: 630, alt: SITE_TITLE };

type OgImage = { url: string; width?: number; height?: number; alt?: string };

/** Plain one-line text, cut at a word boundary — for descriptions built from catalogue copy. */
export function summarize(text: string | null | undefined, max = 200): string | undefined {
  const t = (text ?? "").replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
  if (!t) return undefined;
  if (t.length <= max) return t;
  const cut = t.slice(0, max - 1);
  return `${cut.slice(0, cut.lastIndexOf(" ") > max * 0.6 ? cut.lastIndexOf(" ") : cut.length)}…`;
}

/**
 * Page metadata with matching Open Graph + X (Twitter) card tags and a
 * canonical URL. `title` is the page name (the layout template adds "· NEXORA"
 * to <title>); pass `absoluteTitle` for the home page.
 */
export function pageMetadata({
  title,
  description = SITE_DESCRIPTION,
  path,
  images,
  absoluteTitle,
}: {
  title?: string;
  description?: string;
  path: string;
  images?: OgImage[];
  absoluteTitle?: boolean;
}): Metadata {
  const shareTitle = !title || absoluteTitle ? (title ?? SITE_TITLE) : `${title} · ${SITE_NAME}`;
  const shareImages = images?.length ? images : [DEFAULT_OG_IMAGE];
  return {
    title: absoluteTitle ? { absolute: shareTitle } : title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: "en_PK",
      url: path,
      title: shareTitle,
      description,
      images: shareImages,
    },
    twitter: {
      card: "summary_large_image",
      title: shareTitle,
      description,
      images: shareImages.map((i) => ({ url: i.url, alt: i.alt })),
    },
  };
}
