import type { Config } from "tailwindcss";

/**
 * NEXORA design tokens — taken verbatim from the approved Stitch
 * "Concept 2 — Clean Minimal Marketplace" screens (Nordic Minimalist Commerce).
 * Do not add colours here without design sign-off.
 */
const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#002113",
        "secondary-fixed": "#dce2f7",
        "inverse-on-surface": "#ebf1ff",
        "surface-container-highest": "#dce2f3",
        "on-tertiary-container": "#f5fff6",
        "primary-fixed-dim": "#68dba9",
        "on-background": "#151c27",
        "primary-fixed": "#85f8c4",
        "surface-bright": "#f9f9ff",
        tertiary: "#006947",
        surface: "#f9f9ff",
        "secondary-fixed-dim": "#c0c6db",
        "on-secondary-container": "#5c6274",
        "surface-tint": "#006c4a",
        "tertiary-container": "#00855b",
        "tertiary-fixed": "#6ffbbe",
        "on-surface-variant": "#3d4a42",
        "on-primary-container": "#f5fff7",
        "surface-dim": "#d3daea",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-container": "#d9dff5",
        background: "#f9f9ff",
        "on-primary-fixed-variant": "#005137",
        "error-container": "#ffdad6",
        "outline-variant": "#bccac0",
        secondary: "#575e70",
        "on-secondary-fixed-variant": "#404758",
        "on-error": "#ffffff",
        primary: "#006948",
        "on-primary-fixed": "#002114",
        "on-surface": "#151c27",
        "inverse-primary": "#68dba9",
        "on-secondary-fixed": "#141b2b",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-container": "#00855d",
        "surface-container": "#e7eefe",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container-high": "#e2e8f8",
        error: "#ba1a1a",
        "surface-variant": "#dce2f3",
        outline: "#6d7a72",
        "inverse-surface": "#2a313d",
        "on-error-container": "#93000a",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        "margin-desktop": "3rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-xl": "2rem",
        margin: "1rem",
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
        "margin-tablet": "1.5rem",
      },
      fontFamily: {
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg-mobile": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "price-md": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "price-lg": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "price-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "price-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
