"""Builds supabase/seed_demo_catalog.sql from the DummyJSON demo dataset (MIT).

Source: https://github.com/Ovi/DummyJSON (database/products.json). Images are
served from cdn.dummyjson.com, which exists for demo/testing storefronts.
Ratings and sold counts are NOT copied — they come from real reviews/orders.
Usage: python3 scripts/build-demo-catalog.py path/to/products.json
"""
import json, re, sys

USD_TO_PKR = 280
# groceries are much cheaper locally than the dataset's USD prices suggest
CATEGORY_RATE = {"groceries": 90}

# dataset category -> (parent slug, sub slug, sub name, icon)
CATS = {
    "smartphones": ("electronics", "mobiles-tablets", None, None),
    "tablets": ("electronics", "mobiles-tablets", None, None),
    "laptops": ("electronics", "laptops", "Laptops", "laptop_mac"),
    "mobile-accessories": ("electronics", "mobile-accessories", "Mobile Accessories", "cable"),
    "mens-watches": ("apparel", "watches", "Watches", "watch"),
    "womens-watches": ("apparel", "watches", "Watches", "watch"),
    "mens-shirts": ("apparel", "mens-shirts", "Men's Shirts", "checkroom"),
    "tops": ("apparel", "womens-wear", "Women's Wear", "styler"),
    "womens-dresses": ("apparel", "womens-wear", "Women's Wear", "styler"),
    "womens-bags": ("apparel", "bags", "Bags", "shopping_bag"),
    "womens-jewellery": ("apparel", "jewellery", "Jewellery", "diamond"),
    "sunglasses": ("apparel", "sunglasses", "Sunglasses", "eyeglasses"),
    "mens-shoes": ("footwear", "mens-shoes", "Men's Shoes", "steps"),
    "womens-shoes": ("footwear", "womens-shoes", "Women's Shoes", "steps"),
    "beauty": ("beauty", "makeup", "Makeup", "brush"),
    "skin-care": ("beauty", "skin-care", "Skin Care", "face"),
    "fragrances": ("beauty", "fragrances", None, None),
    "furniture": ("home-living", "furniture", "Furniture", "chair"),
    "home-decoration": ("home-living", "home-decor", "Home Decor", "home"),
    "kitchen-accessories": ("home-living", "kitchen-accessories", "Kitchen Accessories", "skillet"),
    "groceries": ("pantry", "fresh-groceries", "Fresh & Groceries", "nutrition"),
    "sports-accessories": ("sports", "sports-equipment", "Sports Equipment", "sports_tennis"),
}
SKIP = {"vehicle", "motorcycle"}


def q(s):
    return "null" if s is None else "'" + str(s).replace("'", "''") + "'"


def slugify(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")[:70]


def nice_price(usd, category=""):
    pkr = usd * CATEGORY_RATE.get(category, USD_TO_PKR)
    if pkr < 1000:
        return max(99, int(round(pkr / 10.0)) * 10 - 1)
    return int(round(pkr / 100.0)) * 100 - 1


def main(path):
    data = [p for p in json.load(open(path)) if p["category"] not in SKIP]
    out = []
    out.append("-- NEXORA demo catalogue (generated by scripts/build-demo-catalog.py)")
    out.append("-- Source: DummyJSON demo dataset (MIT) — images from cdn.dummyjson.com.")
    out.append("-- Safe to run more than once. Replace with your real products before launch.")
    out.append("-- Remove later with:  delete from public.products where 'demo' = any(tags);\n")

    out.append("insert into public.categories (name, slug, icon, sort_order) values ('Sports', 'sports', 'sports_tennis', 9) on conflict (slug) do nothing;")
    subs = {}
    for parent, sub, name, icon in CATS.values():
        if name:
            subs[sub] = (parent, name, icon)
    for i, (sub, (parent, name, icon)) in enumerate(sorted(subs.items())):
        out.append(
            f"insert into public.categories (parent_id, name, slug, icon, sort_order) "
            f"select id, {q(name)}, {q(sub)}, {q(icon)}, {20 + i} from public.categories where slug = {q(parent)} "
            f"on conflict (slug) do nothing;"
        )

    brands = sorted({p.get("brand") for p in data if p.get("brand")})
    for b in brands:
        out.append(f"insert into public.brands (name, slug, short_code) values ({q(b)}, {q(slugify(b))}, {q(b[:2].upper())}) on conflict (slug) do nothing;")

    seen = set()
    flash = {p["id"] for p in sorted(data, key=lambda p: -p.get("discountPercentage", 0))[:8]}
    featured_ids = {p["id"] for p in data if p["id"] % 9 == 0}
    for p in data:
        _, sub, _, _ = CATS[p["category"]]
        slug = slugify(p["title"])
        if slug in seen:
            slug = f"{slug}-{p['id']}"
        seen.add(slug)
        price = nice_price(p["price"], p["category"])
        disc = p.get("discountPercentage", 0) or 0
        compare = int(round(price / (1 - disc / 100) / 100.0)) * 100 if disc >= 5 else None
        if compare is not None and compare <= price:
            compare = None
        specs = []
        if p.get("brand"):
            specs.append({"label": "Brand", "value": p["brand"]})
        if p.get("warrantyInformation"):
            specs.append({"label": "Warranty", "value": p["warrantyInformation"]})
        if p.get("returnPolicy"):
            specs.append({"label": "Returns", "value": p["returnPolicy"]})
        if p.get("weight"):
            specs.append({"label": "Weight", "value": f"{p['weight']} g"})
        tags = ["demo", p["category"]] + [t for t in p.get("tags", []) if isinstance(t, str)]
        tags_sql = "array[" + ",".join(q(t.lower()) for t in tags) + "]::text[]"
        is_flash = p["id"] in flash
        short = p["description"].split(". ")[0][:150]
        out.append(
            "insert into public.products (slug, name, vendor_id, brand_id, category_id, price, compare_at_price, stock, badges, "
            "is_featured, is_flash_deal, flash_deal_ends_at, flash_deal_stock_total, short_description, description, specs, tags) "
            f"select {q(slug)}, {q(p['title'])}, v.id, b.id, c.id, {price}, {compare if compare else 'null'}, {max(int(p.get('stock', 20)), 5)}, "
            f"'{{}}'::text[], {str(p['id'] in featured_ids).lower()}, {str(is_flash).lower()}, "
            f"{'now() + interval ' + q('5 days') if is_flash else 'null'}, {max(int(p.get('stock', 20)), 5) if is_flash else 'null'}, "
            f"{q(short)}, {q(p['description'])}, {q(json.dumps(specs))}::jsonb, {tags_sql} "
            f"from public.vendors v cross join public.categories c left join public.brands b on b.slug = {q(slugify(p['brand'])) if p.get('brand') else 'null'} "
            f"where v.slug = 'nexora-retail' and c.slug = {q(sub)} on conflict (slug) do nothing;"
        )
        imgs = p.get("images") or [p.get("thumbnail")]
        for i, url in enumerate(imgs[:4]):
            out.append(
                f"insert into public.product_images (product_id, url, alt, sort_order) "
                f"select id, {q(url)}, {q(p['title'])}, {i} from public.products pr where pr.slug = {q(slug)} "
                f"and not exists (select 1 from public.product_images pi where pi.product_id = pr.id and pi.url = {q(url)});"
            )
    open("supabase/seed_demo_catalog.sql", "w").write("\n".join(out) + "\n")
    print(f"{len(data)} products, {len(brands)} brands, {len(subs)} subcategories")


if __name__ == "__main__":
    main(sys.argv[1])
